# Generated by Django 2.0.3 on 2018-03-24 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alternate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_parlamentar', models.IntegerField(null=True, verbose_name='Código Parlamentar')),
                ('descricao_participacao', models.CharField(max_length=100, null=True, verbose_name='Descrição Participação')),
                ('nome_parlamentar', models.CharField(max_length=250, null=True, verbose_name='Nome Parlamentar')),
            ],
            options={
                'verbose_name': 'Alternate',
                'verbose_name_plural': 'Alternates',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código')),
                ('data_inicio', models.DateField(null=True, verbose_name='Data de Início')),
                ('data_fim', models.DateField(null=True, verbose_name='Data de Fim')),
                ('sigla_causa_afastamento', models.CharField(max_length=20, null=True, verbose_name='Sigla Causa Afastamento')),
                ('descricao_causa_afastamento', models.CharField(max_length=250, null=True, verbose_name='Descrição Causa Afastamento')),
                ('data_leitura', models.DateField(null=True, verbose_name='Data Leitura')),
            ],
            options={
                'verbose_name': 'Exercise',
                'verbose_name_plural': 'Exercises',
            },
        ),
        migrations.CreateModel(
            name='Mandate',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código')),
                ('uf', models.CharField(max_length=2, null=True, verbose_name='UF')),
                ('pl_numero', models.IntegerField(null=True, verbose_name='Número Primeira Legislatura')),
                ('pl_data_inicio', models.DateField(null=True, verbose_name='Data Início Primeira Legislatura')),
                ('pl_data_fim', models.DateField(null=True, verbose_name='Data Fim Primeira Legislatura')),
                ('sl_numero', models.IntegerField(null=True, verbose_name='Número Segunda Legislatura')),
                ('sl_data_inicio', models.DateField(null=True, verbose_name='Data Início Segunda Legislatura')),
                ('sl_data_fim', models.DateField(null=True, verbose_name='Data Fim Segunda Legislatura')),
                ('descricao_participacao', models.CharField(max_length=100, null=True, verbose_name='Descrição Participação')),
                ('t_descricao_participacao', models.CharField(max_length=100, null=True, verbose_name='Descrição Participação (Titular)')),
                ('t_codigo_parlamentar', models.IntegerField(null=True, verbose_name='Código Parlamentar (Titular)')),
                ('t_nome_parlamentar', models.CharField(max_length=250, null=True, verbose_name='Nome Parlamentar (Titular)')),
            ],
            options={
                'verbose_name': 'Mandate',
                'verbose_name_plural': 'Mandates',
            },
        ),
        migrations.CreateModel(
            name='Parliamentarian',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código')),
                ('nome', models.CharField(max_length=250, null=True, verbose_name='Nome')),
                ('nome_completo', models.CharField(max_length=250, null=True, verbose_name='Nome Completo')),
                ('sexo', models.CharField(max_length=250, null=True, verbose_name='Sexo')),
                ('forma_tratamento', models.CharField(max_length=100, null=True, verbose_name='Forma de Tratamento')),
                ('url_foto', models.CharField(max_length=255, null=True, verbose_name='Foto')),
                ('url_pagina', models.CharField(max_length=255, null=True, verbose_name='Página')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='E-mail')),
                ('sigla_partido', models.CharField(max_length=20, null=True, verbose_name='Sigla do Partido')),
                ('uf', models.CharField(max_length=2, null=True, verbose_name='UF')),
                ('glossario', models.CharField(max_length=255, null=True, verbose_name='Glossário')),
            ],
            options={
                'verbose_name': 'Parliamentarian',
                'verbose_name_plural': 'Parliamentarians',
                'permissions': (('update_parliamentarians', 'Update Parliamentarians'),),
            },
        ),
        migrations.AddField(
            model_name='mandate',
            name='parliamentarian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='senator.Parliamentarian', verbose_name='Parliamentarian'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='mandate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='senator.Mandate', verbose_name='Mandate'),
        ),
        migrations.AddField(
            model_name='alternate',
            name='mandate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='senator.Mandate', verbose_name='Mandate'),
        ),
        migrations.AlterUniqueTogether(
            name='alternate',
            unique_together={('mandate', 'codigo_parlamentar')},
        ),
    ]
